#:import Factory kivy.factory.Factory

<MainScreen>:
    canvas.before:
        Color:
            rgba: 204/255, 204/255, 204/255, 1
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        opacity: 0.5
        Camera:
            id: camera
            allow_stretch: True
            keep_ratio: False
            resolution: 360, 640
            play: True

    BoxLayout:
        orientation: 'vertical'
        spacing: .1
        Label:
            size_hint_y: 0.1
            text: 'PhotoGraph your picture!'
            font_style: 'Bahnschrift'
            canvas.before:
                Color:
                    rgba: 251/255, 176/255, 59/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
        Label:
            opacity: 0.4
            id: imglbl
            canvas.before:
                Color:
                    rgba: 102/255, 102/255, 102/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            font_style: 'Bahnschrift'
            text: ''
            size_hint_y: .1
        BoxLayout:
            size_hint_y: .1
            Widget:
                size_hint_x: .1
            Label:
                size_hint_x: .3
                text: 'Count of your graphs:'
            Slider:
                size_hint_x: .4
                id: temp
                min: 1
                max: 5
                value: 1
                step: 1
                on_value: root.get_graph_count(temp.value)
            Label:
                size_hint_x: .1
                id: slide_val
                text: '{}'.format(temp.value)
            Widget:
                size_hint_x: .1
        Image:  # lIke a Camera span
            source: 'images/border_red.png'
            size_hint_y: 0.5
            opacity: 0.3
        Widget:
            size_hint_y: .1
        BoxLayout:
#            opacity: .4
            size_hint_y: 0.1
            orientation: 'horizontal'
            AnchorLayout:
                size_hint_x: 1.2401
                anchor_x: 'right'
                anchor_y: 'center'
                Button:
                    id: img_btn
                    size_hint: None, None
                    size: 65, 65
                    canvas.before:
                        Color:
                            rgb: 152/255, 152/255, 153/255, 1
                        Ellipse:
                            pos: self.pos
                            size: self.size
                    canvas.after:
                        Color:
                            rgb: 230/255, 230/255, 230/255, 1
                        Ellipse:
                            pos: self.pos[0] + 5, self.pos[1] + 5
                            size: self.size[0] - 10, self.size[1] - 10
                    background_color: 0, 0, 0, 0
    #                 152/255, 152/255, 153/255, 1

                    on_press:
                        root.ids.imglbl.text = 'Please, wait, big image can take a long time'
                        root.ok = False
                        root.onCameraClick()
                        app.rs.update_image()
            AnchorLayout:
                anchor_x: 'center'
                anchor_y: 'bottom'
                Button:
                    id: loadbtn

                    text: 'Load File'
                    background_color: 1, 0, 0, .4
                    size_hint: None, None
                    size: 60, 60
                    on_press:
                        self.background_color = (1.0, 0.0, 0.0, .87)
                        self.size = (65, 65)
                        self.text = 'Please, wait'
                        root.load_file()

                    on_release:
                        self.background_color = (1, 0, 0, .4)
                        self.size = (60, 60)
                        self.text = 'Load file'
                        app.rs.update_image()


        Widget:
            size_hint_y: 0.1


<StartScreen>:
    canvas.before:
        Color:
            rgba: 102/255, 102/255, 102/255, 1
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        opacity: 0
        Button:
            on_press:
                root.ids.label_start.text = 'Loading, please wait'
            on_release:
                root.switchToNextScreen()
    BoxLayout:
        orientation: 'vertical'
        Widget:
            size_hint_y: 0.1
            canvas.before:
                Color:
                    rgba: 251/255, 176/255, 59/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
        Widget:
            size_hint_y: 0.2
        Image:
            id: logo_img
            size_hint_y: 0.5
            source: 'images/logo2.png'

        Widget:
            size_hint_y: 0.05

        Label:
            id: label_start
            size_hint_y: 0.4
            text: 'Press to continue'


<ResultScreen>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: 204/255, 204/255, 204/255, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            size_hint_y: 0.1
            text: 'Nice picture:)'
            font_style: 'Bahnschrift'

            canvas.before:
                Color:
                    rgba: 251/255, 176/255, 59/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
        BoxLayout:
            orientation: 'horizontal'
            Button:
                size_hint_x: .13
                text: '<'
                on_release:
                    root.ids.selfie_img.source = root.prev_img()
                    root.update_image()
            Image:
                id: selfie_img
                nocache: True
                source: root.img_source
            Button:
                size_hint_x: .13
                text: '>'
                on_release:
                    root.ids.selfie_img.source = root.next_img()
                    root.update_image()
        Widget:
            size_hint_y: 0.05
        BoxLayout:
            size_hint_y: 0.1
            orientation: 'horizontal'
            Widget:
                size_hint_x: .1
            Button:
                text: 'Predict'
                size_hint_x: .35
                on_release: root.show_popup()
            Widget:
                size_hint_x: 0.1
            Button:
                text: 'Save Plot'
                size_hint_x: .35
                on_release: root.save_plot()
            Widget:
                size_hint_x: .1
        Widget:
            size_hint_y: .05
        BoxLayout:
            size_hint_y: 0.1
            orientation: 'horizontal'
            Widget:
                size_hint_x: .1
            Button:
                text: 'Back'
                size_hint_x: .35
                on_press: root.manager.current = 'main_screen'
            Widget:
                size_hint_x: .1
            Button:
                text: 'Save csv'
                size_hint_x: .35
                on_press: root.save_data()
            Widget:
                size_hint_x: .1
        Widget:
            size_hint_y: .1


<PopupScreen>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: 102/255, 102/255, 102/255, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Button:
            text: 'Linear regression'
            size_hint: .7, .2
            pos_hint: {"x": .1, "y": .7}
            on_release:
                root.process_linear()
                app.rs.popupWindow.dismiss()
                app.ps.update_prediction_image()
                app.sm.current = 'predict_screen'

        Button:
            text: 'Polynomial regression'
            size_hint: .7, .2
            pos_hint: {"x": .1, "y": .4}
            on_release:
                root.process_polynomial()
                app.rs.popupWindow.dismiss()
                app.ps.update_prediction_image()
                app.sm.current = 'predict_screen'

        Button:
            text: 'AI prediction(Not Implemented)'
            size_hint: .7, .2
            pos_hint: {"x": .1, "y": .1}
            on_release:
                root.process_ai()
                app.rs.popupWindow.dismiss()
                app.ps.update_prediction_image()
                app.sm.current = 'predict_screen'


<PredictScreen>:
    BoxLayout:
        canvas.before:
            Color:
                rgba: 204/255, 204/255, 204/255, 1
            Rectangle:
                pos: self.pos
                size: self.size
        orientation: 'vertical'
        Label:
            size_hint_y: 0.1
            text: "Yeah! You are here!"
            font_style: 'Bahnschrift'
            canvas.before:
                Color:
                    rgba: 251/255, 176/255, 59/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
        Image:
            size_hint_y: .55
            id: res_img
            source: 'prediction.png'
        Widget:
            size_hint_y: .05
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: .1
            Widget:
                size_hint_x: .1
            Button:
                size_hint_y:
                text: 'Back'
                size_hint_x: .35
                on_release: app.sm.current = 'result_screen'
            Widget:
                size_hint_x: .1
            Button:
                text: 'Save'
                size_hint_x: .35
                on_release: root.save_to_gallery()
            Widget:
                size_hint_x: .1
        Widget:
            size_hint_y: .1

<DirScreen>:
    TextInput:
        id: input
        hint_text:'Enter text'
        pos_hint: {'center_x': 0.5, 'center_y': 0.705}
        size_hint: 0.95, 0.5

    Button:
        size_hint: .6, .2
        pos_hint: {'x': .2, 'y': .1}
        text: 'Done'
        on_press:
            app.ms.leave_input(root.ids.input.text)
        on_release:
            app.ms.popupWindow.dismiss()